task1
Konstantsiy/go-internship pull request #1
Opened 2021-03-31 12:14 UTC by Konstantsiy

Implemented functions that reverses and capitalizes a string

2021-03-31 12:29 UTC, GoRunMaxim commented
Good job! Couple notes for you: 

1. Probably you want to change README.md file: you could take a look on this web-site: https://www.makeareadme.com
2. I caught some errors with golangci-linter. You should add comment for exported functions.

2021-03-31 12:30 UTC, GoRunMaxim commented
Also, I suggest you to take a look on this webpage: https://chris.beams.io/posts/git-commit/

2021-03-31 19:08 UTC, GoRunMaxim commented
1. Good, your commits looks much more better, but read this: https://chris.beams.io/posts/git-commit/

2021-03-31 19:14 UTC, Konstantsiy commented
> 1. Good, your commits looks much more better, but read this: https://chris.beams.io/posts/git-commit/
> 2. Did you run the tests? It failed, didn't it?

One test was intentionally made incorrectly to show that the function only works with Latin and Cyrillic

2021-03-31 19:18 UTC, GoRunMaxim commented
> > 1. Good, your commits looks much more better, but read this: https://chris.beams.io/posts/git-commit/
> > 2. Did you run the tests? It failed, didn't it?
> 
> One test was intentionally made incorrectly to show that the function only works with Latin and Cyrillic

Well, usually, we run all tests to see that they are working correctly. They shout not failed. Could we find the way for our function to work not only with Latin and Cyrillic?

2021-03-31 19:23 UTC, GoRunMaxim commented
I don't really think that we need "task1" and "src" directories, do we? So you could remove them.

2021-03-31 19:33 UTC, Konstantsiy commented
> > > 1. Good, your commits looks much more better, but read this: https://chris.beams.io/posts/git-commit/
> > > 2. Did you run the tests? It failed, didn't it?
> > 
> > 
> > One test was intentionally made incorrectly to show that the function only works with Latin and Cyrillic
> 
> Well, usually, we run all tests to see that they are working correctly. They shout not failed. Could we find the way for our function to work not only with Latin and Cyrillic?

2021-03-31 19:34 UTC, Konstantsiy commented
> I don't really think that we need "task1" and "src" directories, do we? So you could remove them.



> > > 1. Good, your commits looks much more better, but read this: https://chris.beams.io/posts/git-commit/
> > > 2. Did you run the tests? It failed, didn't it?
> > 
> > 
> > One test was intentionally made incorrectly to show that the function only works with Latin and Cyrillic
> 
> Well, usually, we run all tests to see that they are working correctly. They shout not failed. Could we find the way for our function to work not only with Latin and Cyrillic?

I think I found a solution: using an internal library for unicode: https://golang.org/pkg/unicode

2021-03-31 19:40 UTC, GoRunMaxim commented
> > I don't really think that we need "task1" and "src" directories, do we? So you could remove them.
> 
> > > > 1. Good, your commits looks much more better, but read this: https://chris.beams.io/posts/git-commit/
> > > > 2. Did you run the tests? It failed, didn't it?
> > > 
> > > 
> > > One test was intentionally made incorrectly to show that the function only works with Latin and Cyrillic
> > 
> > 
> > Well, usually, we run all tests to see that they are working correctly. They shout not failed. Could we find the way for our function to work not only with Latin and Cyrillic?
> 
> I think I found a solution: using an internal library for unicode: https://golang.org/pkg/unicode

You could try it and see, if it works with Belorussian language.

2021-03-31 20:01 UTC, Konstantsiy commented
Now all tests work, not only with Latin and Cyrillic!

2021-03-31 20:12 UTC, GoRunMaxim commented
Looks good! A couple advices: 

1.  "go mod tidy" may help you to clean up unused dependencies
2.  Probably commits should start with such words as "Add", "Fix". 
3.  What happened if we try to capitalize empty string?

2021-04-01 13:55 UTC, papahmsolo requested changes
Nice job!

See comments below

2021-04-01 13:55 UTC, papahmsolo commented on go.mod
> +go 1.13
Let's give this module a name that describes its purpose

2021-04-01 13:55 UTC, papahmsolo commented on README.md
> +
Let's describe this module from the user's perspective? What problems does it solve, what is it capable of?

2021-04-01 13:55 UTC, papahmsolo commented on main.go
> +package main
- Package comment
- This should be a library you suppose to import into your project, so let's rename the package and the file name if you want

2021-04-01 13:55 UTC, papahmsolo commented on main_test.go
> +		}
`%q` would look nicer for empty strings and leading/trailing spaces.

2021-04-01 14:10 UTC, papahmsolo commented
- Fix test
- Add Examples

2021-04-02 09:16 UTC, papahmsolo approved these changes

2021-04-02 09:32 UTC, papahmsolo approved these changes

2021-04-02 09:59 UTC, merged